# Generated by Django 5.1.5 on 2025-01-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'verbose_name': 'Currency Pair',
                'verbose_name_plural': 'Currency Pairs',
            },
        ),
    ]
