# Generated by Django 5.1.5 on 2025-01-26 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_canceled_at_order_completed_at_order_pnl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='passwd',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
