# Generated by Django 5.1.5 on 2025-02-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tradingaccount_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='action',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4),
        ),
    ]
