# Generated by Django 5.1.5 on 2025-01-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_notification_title_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='untitled notifications', max_length=255),
            preserve_default=False,
        ),
    ]
