# Generated by Django 5.1.5 on 2025-02-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
