# Generated by Django 5.1.5 on 2025-02-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_action'),
        ('api', '0007_delete_userprofile'),
    ]

    operations = [
    ]
