# Generated by Django 5.1.5 on 2025-02-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_0004_order_action_0007_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
